import type { IJob } from "@/types/JobType";
import type { Company, IUser } from "@/types/UserType";

// Data Perusahaan yang sudah terdaftar
export const dummyCompanies: Company[] = [
    {
        id: "comp-101",
        name: "TechCorp Solutions",
        slug: "techcorp-solutions",
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=TC",
        industry: "Software Development",
        description: "Membangun masa depan digital dengan AI dan Cloud.",
        website: "https://techcorp.example.com",
        address: "Jakarta Selatan, Indonesia",
        verified: true,
        employeeCount: "201-500",
    },
    {
        id: "comp-102",
        name: "Creative Pixel Studio",
        slug: "creative-pixel",
        logo: "https://api.dicebear.com/7.x/initials/svg?seed=CP",
        industry: "Design & Multimedia",
        description: "Agensi desain pemenang penghargaan.",
        website: "https://creativepixel.example.com",
        address: "Bandung, Indonesia",
        verified: false,
        employeeCount: "11-50",
    },
];

// Data User yang sudah login (Mock Auth State)
export const currentUser: IUser = {
    id: "user-001",
    name: "HR Manager TechCorp",
    email: "hr.manager@techcorp.com",
    role: "candidate",
    createdAt: new Date("2026-01-01T00:00:00Z"),
    displayName: "HR Manager TechCorp",
    photoURL: "https://api.dicebear.com/7.x/initials/svg?seed=HRM",
    uid: "user-001",
};

// export const dummyUsers: IUser[] = [
// 	{
// 		id: "u1",
// 		email: "hrd1@company.com",
// 		name: "Budi HR",
// 		role: "candidate",
// 		createdAt: new Date("2026-01-01"),
// 		displayName: "Budi HR",

// 	},
// 	{
// 		id: "u2",
// 		email: "hrd2@startup.com",
// 		name: "Sari HR",
// 		role: "candidate",
// 		createdAt: new Date("2026-01-02"),
// 		displayName: "Budi HR",
// 	},
// 	{
// 		id: "u3",
// 		email: "andi@mail.com",
// 		name: "Andi Saputra",
// 		role: "candidate",
// 		createdAt: new Date("2026-01-03"),
// 		displayName: "Budi HR",
// 	},
// 	{
// 		id: "u4",
// 		email: "rina@mail.com",
// 		name: "Rina Putri",
// 		role: "candidate",
// 		createdAt: new Date("2026-01-04"),
// 		displayName: "Budi HR",
// 	},
// 	{
// 		id: "u5",
// 		email: "fajar@mail.com",
// 		name: "Fajar Nugraha",
// 		role: "candidate",
// 		createdAt: new Date("2026-01-05"),
// 		displayName: "Fajar Nugraha",
// 	},
// ];

export const dummyJobs: IJob[] = [
    {
        id: "j1",
        title: "Frontend Vue Developer",
        description: "Mengembangkan dashboard menggunakan Vue 3.",
        location: "Makassar",
        salaryMin: 6000000,
        salaryMax: 9000000,
        jobType: "full-time",
        createdBy: "u1",
        createdAt: new Date("2026-02-01"),
        // companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TC",
        // companyName: "TechCorp Solutions",
    },
    {
        id: "j2",
        title: "Backend Node.js Developer",
        description: "Membangun REST API dan integrasi Firebase.",
        location: "Jakarta",
        salaryMin: 7000000,
        salaryMax: 10000000,
        jobType: "full-time",
        createdBy: "u2",
        createdAt: new Date("2026-02-02"),
        companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=CP",
        companyName: "Creative Pixel Studio",
    },
    {
        id: "j3",
        title: "UI/UX Designer",
        description: "Mendesain tampilan aplikasi job portal.",
        location: "Remote",
        salaryMin: 5000000,
        salaryMax: 8000000,
        jobType: "contract",
        createdBy: "u1",
        createdAt: new Date("2026-02-03"),
        companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TC",
        companyName: "TechCorp Solutions",
    },
    {
        id: "j4",
        title: "Digital Marketing Specialist",
        description: "Mengelola campaign dan SEO.",
        location: "Bandung",
        salaryMin: 4000000,
        salaryMax: 7000000,
        jobType: "full-time",
        createdBy: "u2",
        createdAt: new Date("2026-02-04"),
        companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=CP",
        companyName: "Creative Pixel Studio",
    },
    {
        id: "j5",
        title: "Mobile App Developer",
        description: "Mengembangkan aplikasi mobile menggunakan Flutter.",
        location: "Surabaya",
        salaryMin: 6500000,
        salaryMax: 9500000,
        jobType: "full-time",
        createdBy: "u1",
        createdAt: new Date("2026-02-05"),
        companyLogo: "https://api.dicebear.com/7.x/initials/svg?seed=TC",
        companyName: "TechCorp Solutions",
    },
];
